### ISSUE TITLE
Can't change the scripting folder

### ISSUE THREAD

**Issue by typoman** [mrecord/ScriptLauncher#1]
I was testing the extension on RF 4.2 on OSX 12.3.1 and I got this trackback when I wanted to change the scripting folder in the preferences:

```
  File "ScriptLauncher.py", line 161, in writePreferences
AttributeError: 'str' object has no attribute 'get'
```

**Comment by mrecord** [comment]
Thank you for catching this and providing a fix! You are awesome.
